# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-18 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='smoke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadtime', models.DateTimeField(auto_now=True)),
                ('tvalue', models.TextField(default='-1')),
                ('longitude', models.TextField(default='0')),
                ('latitude', models.TextField(default='0')),
            ],
        ),
    ]
