# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-30 06:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smoke', '0002_auto_20180321_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smoke',
            name='latitude',
            field=models.TextField(default='40'),
        ),
        migrations.AlterField(
            model_name='smoke',
            name='longitude',
            field=models.TextField(default='116'),
        ),
        migrations.AlterField(
            model_name='smoke',
            name='uploadtime',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 30, 14, 12, 7, 639000)),
        ),
        migrations.AlterField(
            model_name='smoke',
            name='value',
            field=models.TextField(default='-1'),
        ),
    ]
