# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-09 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smoke', '0003_auto_20180330_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smoke',
            name='latitude',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='smoke',
            name='longitude',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='smoke',
            name='uploadtime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
